---
title: "WineCleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Dependencies
```{r}
library("tidyverse")
```
### Bring in the Wine
```{r}
wine_raw <-read_csv("winemag-data-130k-v2.csv")
```
### We only want the US wineries for the sake of simplicity
```{r}
unique(wine_raw$country)
wine_US = subset(wine_raw,country=="US")
wine_US_clean = na.omit(wine_US)
```

### How many wine varieties do we have?
```{r}
num_types = unique(wine_US_clean$variety)
paste("There are", length(num_types), "wine types in our dataset")

wine_by_type = as.data.frame(table(wine_US_clean$variety))
wine_by_type = wine_by_type[order(-wine_by_type$Freq),]

# if we just take the top 10 wines in the US
paste("The number of records for the top 10 varietals would give us", sum(wine_by_type$Freq[1:10]), "rows")
```
### pull the rows for just the top 10 varietals 
```{r}
wine_10 = as.data.frame(subset(wine_US_clean, variety == wine_by_type$Var1[1]|variety == wine_by_type$Var1[2]|
                                 variety == wine_by_type$Var1[3]|variety == wine_by_type$Var1[4]|
                                 variety == wine_by_type$Var1[5]|variety == wine_by_type$Var1[6]|
                                 variety == wine_by_type$Var1[7]|variety == wine_by_type$Var1[8]|
                                 variety == wine_by_type$Var1[9]|variety == wine_by_type$Var1[10]))
write.csv(wine_10, file = "WineTop10.csv")
```
```{r}
# we want another DF that has just states, average price of wine, average score
wine_us_state = unique(wine_10$province)
wine_by_state = as.data.frame(group_by(wine_US, province))
wine_by_state_price = mean(wine_by_state$price)

wine_by_state_avg = wine_US %>% 
  group_by(province) %>% 
  summarize(avg.price=mean(price, na.rm= TRUE), avg.score=mean(points, na.rm = TRUE))
wine_by_state_avg
```
```{r}
# Write the data to a CSV
write.csv(wine_10, file = "WineTop10.csv")
write.csv(wine_by_state_avg, file = "Wine_by_State.csv")
```
